import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,cp,readFile,stat,unlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
import {publishBatch,type Batch} from '../src/trigger/hk-job-hunt/package.js';
import {reviewed} from './audit-fixture.js';
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),'hk-test-'));await mkdir(path.join(root,'cv'),{recursive:true});await cp('cv/Adam_Kanevsky_CV.pdf',path.join(root,'cv/Adam_Kanevsky_CV.pdf'));await cp('.claude',path.join(root,'.claude'),{recursive:true});return root;}
const batch:Batch={week:'2026-week-37',createdAt:'2026-09-11T01:00:00Z',reserveCount:1,notes:['Test only.'],applications:[],emails:[{id:'test-note',kind:'cold',company:'Test company',person:'Test recipient',email:null,variant:'B-teardown',subject:'A check before the next deposit',body:"Hi Alex,\n\nYour guide separates the payment routes. I wrote a note on the choice. I may have missed a detail.\n\nAdam\nCV attached.",holdReasons:['Test data.'],artefact:{title:'Payment choice',sections:[{heading:'Proposal',text:'Show the required evidence beside each route. This is a proposal to test.'}],sources:[{url:'https://example.com/',title:'Test fixture',checkedAt:'2026-09-11',note:'Synthetic example only.'}]}}]};
test('real package has one PDF sample and both MIME attachments; retries are identical',async()=>{const root=await fixture();const b=structuredClone(batch);b.emails=b.emails.map(reviewed);const first=await publishBatch(b,root);assert.equal(first.emails.length,1);const eml=await readFile(path.join(root,'outbox',b.week,'test-note.eml'),'utf8');assert.equal((eml.match(/Content-Disposition: attachment/g)||[]).length,2);assert.ok(eml.includes('X-Unsent: 1'));assert.ok(!/^To:/m.test(eml));assert.equal((await publishBatch(b,root)).fingerprint,first.fingerprint);assert.ok(first.emails[0].attachmentBytes<1000000);await unlink(path.join(root,'outbox',b.week+'.md'));await publishBatch(b,root);assert.ok((await stat(path.join(root,'outbox',b.week+'.md'))).isFile());});
test('a third follow-up is excluded from output, not merely labelled held',async()=>{const root=await fixture();const b=structuredClone(batch);b.emails[0].kind='follow_up';b.emails[0].email='test@example.com';const m=await publishBatch(b,root,[{company:'Test company',email:'test@example.com',status:'sent',date_sent:'2026-08-01',follow_up_due:'2026-08-08',follow_up_count:2}]);assert.equal(m.emails.length,0);assert.equal(m.excluded.length,1);await assert.rejects(stat(path.join(root,'outbox',batch.week,'test-note.eml')));});
test('missing CV prevents publication',async()=>{const root=await fixture();await unlink(path.join(root,'cv/Adam_Kanevsky_CV.pdf'));await assert.rejects(publishBatch(batch,root));await assert.rejects(stat(path.join(root,'outbox',batch.week+'.md')));});
test('changed same-week batch cannot overwrite the reviewed version',async()=>{const root=await fixture();await publishBatch(batch,root);const b=structuredClone(batch);b.notes.push('Changed');await assert.rejects(publishBatch(b,root),/already published/);});
test('audited CV-only mail contains the actual CV and no sample',async()=>{
 const root=await fixture();const b=structuredClone(batch);const e=b.emails[0];e.approach='cv_only';delete e.artefact;e.body='Hi Alex, I wrote to ask about a junior role. This is a proposal to test. Adam';b.emails=[reviewed(e)];
 const m=await publishBatch(b,root);assert.equal(m.emails.length,1);
 const eml=await readFile(path.join(root,'outbox',b.week,e.id+'.eml'),'utf8');
 assert.equal((eml.match(/Content-Disposition: attachment/g)||[]).length,1);
 const encoded=eml.split('filename="Adam_Kanevsky_CV.pdf"')[1].split('\r\n\r\n')[1].split('\r\n--')[0];
 assert.deepEqual(Buffer.from(encoded,'base64'),await readFile(path.join(root,'cv/Adam_Kanevsky_CV.pdf')));
 await assert.rejects(stat(path.join(root,'outbox',b.week,e.id+'.pdf')));
});
test('unaudited application is excluded rather than handed to Adam to verify',async()=>{
 const root=await fixture();const b=structuredClone(batch);b.emails=[];b.applications=[{id:'unverified-role',company:'Example',title:'Analyst',url:'https://example.com/job',deadline:null,start:'2027',language:'English',eligibility:'Unknown',points:['My background fits the role.'],status:'review',holdReasons:[],source:{url:'https://example.com/job',title:'Role',checkedAt:'2026-09-11',note:'Unverified fixture.'}}];
 const m=await publishBatch(b,root);assert.equal(m.applications,0);assert.equal(m.status,'partial');assert.match(m.excluded[0].reasons[0],/Audit/);
});
